# Generated by Django 5.0.2 on 2025-05-30 14:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExtendedPermission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'extended permission',
                'verbose_name_plural': 'extended permissions',
            },
        ),
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(blank=True)),
                ('display_name', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'role',
                'verbose_name_plural': 'roles',
            },
        ),
        migrations.AlterModelOptions(
            name='user',
            options={'permissions': [('can_view_dashboard', 'Can view dashboard'), ('can_manage_users', 'Can manage users'), ('can_manage_roles', 'Can manage roles')], 'verbose_name': 'user', 'verbose_name_plural': 'users'},
        ),
        migrations.RenameIndex(
            model_name='user',
            new_name='core_user_email_38052c_idx',
            old_name='user_email_idx',
        ),
        migrations.RenameIndex(
            model_name='user',
            new_name='core_user_name_5df803_idx',
            old_name='user_name_idx',
        ),
        migrations.AddField(
            model_name='extendedpermission',
            name='permission',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='auth.permission'),
        ),
        migrations.AddField(
            model_name='role',
            name='group',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='auth.group'),
        ),
    ]
